language: node_js

node_js: 
  - 9
  - 8
  - node

install: true

before_script: 
  - chmod 0777 ./node_modules/.bin/mocha
  - chmod 0777 ./node_modules/.bin/nodemon
  - chmod 0777 ./node_modules/.bin/babel-node

script:
  - npm test
